# Generated by Django 3.1.3 on 2020-11-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phonebook',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('contact_number', models.IntegerField(max_length=10, unique=True)),
                ('iid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
